// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_ANON_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY;

// Validate environment variables
if (!SUPABASE_URL || !SUPABASE_ANON_KEY) {
  throw new Error(
    'Missing Supabase environment variables. ' +
    'Please ensure VITE_SUPABASE_URL and VITE_SUPABASE_ANON_KEY are set in your .env file. ' +
    'Copy .env.example to .env and add your credentials.'
  );
}

// Validate URL format
if (!SUPABASE_URL.startsWith('https://')) {
  throw new Error(
    'Invalid Supabase URL format. URL must start with https://. ' +
    `Received: ${SUPABASE_URL}`
  );
}

// Validate URL is a proper Supabase URL
if (!SUPABASE_URL.includes('supabase.co')) {
  console.warn(
    `Warning: SUPABASE_URL doesn't appear to be a standard Supabase URL. ` +
    `Expected format: https://[project-id].supabase.co`
  );
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_ANON_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});